### ISSUE TITLE
Feature request: API or bookmarklet to a dynamic feed

### ISSUE THREAD

**Issue by helmut72** [mxpv/podsync#105]
It would be cool to have an API or just a bookmarklet, which adds any Youtube video to a dynamic feed. Like dynamic playlists in Music players.

When browsing Youtube and I find a cool video, I don't want to add the whole channel to a new feed.

But I like the idea to have one place for watching all my videos - my prefered Podcast App.

Thanks!

**Comment by hatzel** [comment]
One way to do this is by just adding videos like to a playlist. Works like a charm! You need to be logged into Youtube in your browser though. You could probably even use a private playlist if the api-key is associated with your Youtube account (there is some setting for that), I have not tested that though.

**Comment by helmut72** [comment]
Thanks, but this isn't possible. I'm not logged into the typical accounts (if I have any) when browsing the web with my main Browser.

For some server related services using an API key or any login, it's ok. My server doesn't travel and doing only specific things all the time. Personally I don't want to be tracked - there is no reason.

**Comment by mxpv** [comment]
This would require us a lot of work, I can think of:
- Adding API to add feed.
- Adding some authentication.
- Reworking configuration format to dynamically add new episodes.
- Adding client to invoke API (?) from browser.
- Rework feeds to work on episode level instead of feed level.

The suggested workaround from @hatzel is the best option for now.
Probably Podsync is not right tool for this. Sorry, I don't think it's feasible to satisfy this feature request.
