### ISSUE TITLE
Feature request: crawler mode without web server

### ISSUE THREAD

**Issue by harupong** [mxpv/podsync#159]
I'm using S3 to host files generated by podsync, and it would be great if podsync can be executed like a crawler, which generates the data and then exits.

That way, 

- I can avoid exposing another port of my server to Internet
- podsync does not need to be running in background all the time (I'll use cron to excute podsync and transfer the data)

I know I can use firewall to block access to the port exposed by podsync, but it's always nice IMHO to have less firewall rules and running-in-background processes.

**Comment by mxpv** [comment]
Can you describe your use case ? Why not to just use youtube-dl to download data, sounds like better fit.

**Comment by Mrigank11** [comment]
@mxpv We have a similar use-case. Basically, we want to generate podcast feeds using podsync and serve it using existing solutions like S3 or GH pages.

As far as I can see, podsync server simply serves the data directory. It'd be great to make the server optional so that data can be served by other means.

I can send a PR if you wish.

**Comment by mxpv** [comment]
Sure. Config switch sounds good to me. PRs are always welcome :)
