### ISSUE TITLE
Filtering by episode duration

### ISSUE THREAD

**Issue by Gandulf78** [mxpv/podsync#403]
Hi there. 
Thank you so much for this app. 
I am wondering : is there a way to filter episodes by duration by a setting in config.toml? I am following a feed where I am only interested by long episodes. Is there a way to discard the short ones? Otherwise is it an improvement you could consider?
Thank you.

**Comment by bcarney66** [comment]
I'd like this function as well, but for the opposite reason - I follow some channels that have short videos that I watch, but once or twice a week they have 2-3 hour livestreams that I have no interest in, and they push me towards my bandwidth cap.

**Comment by fqx** [comment]
> Hi there.
> Thank you so much for this app.
> I am wondering : is there a way to filter episodes by duration by a setting in config.toml? I am following a feed where I am only interested by long episodes. Is there a way to discard the short ones? Otherwise is it an improvement you could consider?
> Thank you.

Me too

**Comment by Th0masL** [comment]
Hey ! I've added a PR for this improvement (see #457)

**Comment by Th0masL** [comment]
For the moment there's a bug with the current build jobs on this repo.

Because of that, I've updated my [Th0masL/podsync](https://github.com/Th0masL/podsync/) repo and released a new Docker Image.

The following Docker Image supports duration filters : `th0masl/podsync:v2.4.2-2023-01-02`.

You should be able to switch back to `mxpv/podsync:<version>` when @mxpv will have merged the PR #458 that fixes the CI/CD pipeline builds.

**Comment by pagdot** [comment]
I already merged and released :) Although it seems like duration is in ms and not in s
