### ISSUE TITLE
Add filter support

### ISSUE THREAD

**Issue by kgraefe** [mxpv/podsync#63]
I'd like to filter video lists by keywords before they get downloaded on the server, similiar to http://re.rephrase.net/filter/?p=filters which I use for RSS feeds.

Example: I'm only interested in the Debrief videos in https://www.youtube.com/user/MERCEDESAMGPETRONAS/videos . But since they don't offer a separate playlist for that I'd have to store all the other videos on my server, too...

**Comment by amcgregor** [comment]
From the [example approach I demonstrated in another issue thread](https://gist.github.com/amcgregor/666fa2b3ce673ab15ebcf2420353374b) filtering is possible using the full suite of `YouTube-dl` command-line arguments.  Example: [Achievement Hunter excluding "behind-the-scenes" / vlog content](https://gist.github.com/amcgregor/666fa2b3ce673ab15ebcf2420353374b#file-pull-sh-L74).  My full set of channels and playlists is far more extensive than demonstrated in that example file (more along the lines of 160 or so channels), and filtering is extensively utilized.  Most _exclude_ using rejection (regular expression) patterns like those, two are more selective and only _include_ specific title patterns.

In your case, a line would need to be added to the indented call to `parallel` such as:

```
youtube-dl ${UNLIMITED} --match-title debrief https://www.youtube.com/user/MERCEDESAMGPETRONAS
```

See also the `--match-filter` option.

**Comment by kgraefe** [comment]
Thanks, I am actually trying to move away from my own self-made youtube-to-rss converter script.

**Comment by amcgregor** [comment]
> Thanks, I am actually trying to move away from my own self-made youtube-to-rss converter script.

Completely fair.

On the gripping hand, `podsync` itself internally uses `youtube-dl` to implement its scraping/ingest tasks.  I'm just going one rung down the ladder with that shell script, which also provides nearly all of the "missing" features (actually: just not exposed) everyone has asked for—inclusion or exclusion filtering, dynamic per-channel/playlist limits, per channel/playlist finely tuned quality settings, control over the level of parallelism, and even the ability to parallelize the `youtube-dl` calls across a cluster of multiple machines/servers.  (`man parallel` ;)

I will admit to the fact that RSS feed generation and ingest are a **huge** part of my day job, processing millions of job offers/opportunities per year both inbound and outbound, so I do have a level of comfort "rolling my own" for this problem that most won't share.  I do hope it shows, at least, that it's _possible_ to expose this option.  💃

**Comment by kgraefe** [comment]
Please stop that. I'm not interested.

**Comment by mxpv** [comment]
@kgraefe do you want filter by title or description (or both)?

**Comment by kgraefe** [comment]
Filter by title would be enough for my use case. I do have another channel where I would want to *exclude* matching episodes, though.

**Comment by hzenginx** [comment]
+1 for this. I follow some channels for only some videos and this would be great

**Comment by amcgregor** [comment]
> Please stop that. I'm not interested.
> …
> Filter by title would be enough for my use case. I do have another channel where I would want to exclude matching episodes, though.

@kgraefe The "hooray" (intentional conveyance of apathy to that initial statement) reaction deserves an explanation.  I understand completely that you aren't interested in the solution to your problem/request, _despite follow-up statements reinforcing your stated desire for a solution_.  The solution I write, on one hand resolves your exact requests, but on the other hand ultimately _isn't for **you**_.  I write the solution out for _anyone who might be willing_ to pick it up and apply it to Podsync in the future, because Podsync _does_ [**literally** use `youtube-dl` to do its work](https://github.com/mxpv/podsync/blob/master/pkg/ytdl/ytdl.go#L43).  Thus this ought to be a "minor" change / patch.  Almost trivial.  Just the addition of two arguments to the `exec` invocation, and appropriate mechanism to configure its use.

I'd do it, but… Go is not a language I've ever used before, so I'm far more likely to cause incidental harm.  I'm a Python girl.  (… and YouTube-dl is Python.)

**Comment by palfrey** [comment]
#92 implements a basic form of title matching if that's of any interest to folks here?
